### ISSUE TITLE
Test error               ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by huangguifeng** [lct1997/BasicSTISR#3]
![image](https://github.com/user-attachments/assets/ee134a3d-27ef-40f9-89ea-fc36c6fd0989)
loading pretrained crnn model from pretrained/crnn.pth
loading pre-trained moran model from pretrained/moran.pth
recognizer_path: None
loading pretrained crnn model from pretrained/crnn.pth
Traceback (most recent call last):
  File "E:\BasicSTISR-master\BasicSTISR-master\main.py", line 45, in <module>
    main(config, args)
  File "E:\BasicSTISR-master\BasicSTISR-master\main.py", line 14, in main
    Mission.train()
  File "E:\BasicSTISR-master\BasicSTISR-master\interfaces\super_resolution.py", line 188, in train
    cascade_images, pre_mask = model_list[0](cascade_images, label_vecs_final.detach())
ValueError: too many values to unpack (expected 2)

**Comment by huangguifeng** [comment]
"tatt", "tpgsr", "tbsrn"       Using these algorithms will cause an error. Changing TSRN to this will allow normal training.
